name: openvla-oft
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.0
      - accelerate==1.8.1
      - annotated-types==0.7.0
      - anyio==4.9.0
      - array-record==0.7.2
      - astunparse==1.6.3
      - attrs==25.3.0
      - bddl==3.6.0
      - cachetools==5.5.2
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - diffusers==0.34.0
      - dlimp==0.0.1
      - dm-tree==0.1.9
      - draccus==0.8.0
      - easydict==1.13
      - einops==0.8.1
      - etils==1.12.2
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - fastapi==0.115.14
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - flash-attn==2.5.5
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - fsspec==2025.5.1
      - future==1.0.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.9.0
      - google-auth==2.40.3
      - google-auth-oauthlib==1.2.2
      - google-pasta==0.2.0
      - grpcio==1.73.1
      - gym==0.26.2
      - gym-notices==0.0.8
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - huggingface-hub==0.33.1
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - jinja2==3.1.6
      - joblib==1.5.1
      - json-numpy==2.1.0
      - jsonlines==4.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupytext==1.17.2
      - keras==2.15.0
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mujoco==3.3.3
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - openexr==3.3.4
      - openvla-oft==0.0.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.1
      - peft==0.15.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - promise==2.3
      - protobuf==4.21.12
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pynput==1.8.1
      - pyopengl==3.1.9
      - pyparsing==3.2.3
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-include==1.4.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - robosuite==1.4.1
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.1.99
      - sentry-sdk==2.32.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.17.2
      - termcolor==3.1.0
      - timm==0.9.10
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.2.0
      - torchaudio==2.2.0
      - torchvision==0.17.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.40.1
      - trimesh==4.6.12
      - triton==2.2.0
      - typeguard==2.13.3
      - typing-extensions==4.14.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.34.3
      - wandb==0.20.1
      - werkzeug==3.1.3
      - wrapt==1.14.1
      - zipp==3.23.0
prefix: /root/miniconda3/envs/openvla-oft
